### ISSUE TITLE
choix d'affichage de pourcentage d'ouverture de volets

### ISSUE THREAD

**Issue by ahyear** [benjaminprevot/jeedom-plugin-connexoon#4]
Bonjour,

J'utilise ce module et j'en suis tres contant.
je voulais savoir si il etais possible d'ajouter l'inversion des valeur d'ouverture?

Actuelllement il y a le pourcentage de fermeture mais j'aimerai pouvoir choisir d'afficher le pourcentage d'ouverture (plus logique a mon gout).

Merci encore et bon courage!

**Comment by benjaminprevot** [comment]
Bonjour @ahyear ,

Merci pour ce retour.

En effet, la valeur retournée actuellement est celle de l'API Somfy :
- 0 => ouvert
- 100 => fermé

Je fais le nécessaire dès que possible afin d'ajouter le paramètre d'inversion de la valeur.

**Comment by benjaminprevot** [comment]
Re-bonjour @ahyear,

Une nouvelle version beta (2020-10-24 19:19:03) est disponible.

Il est maintenant possible d'inverser la commande position dans l'onglet "commandes" des volets.

**Comment by ahyear** [comment]
j'ai aussi remarqué, en connectant ce module a alexa que la aussi c'est inversé. (contrairement au skill connexoon direct sur alexa)
du coup je me demande si il ne serait pas judicieux d'inverser a la source l'information fournie par l'api connexoon...

**Comment by benjaminprevot** [comment]
Bonjour,

En utilisant Alexa, le problème persiste même en inversant la position dans l'onglet "Commandes" des volets ?

**Comment by ahyear** [comment]
ca fonctionne correctement maintenant sans changer de paramétrage. les derniers dev ont du regler le probleme...

**Comment by benjaminprevot** [comment]
Bonne nouvelle ;-)
