### ISSUE TITLE
401 on admin login

### ISSUE THREAD

**Issue by ahyear** [benjaminprevot/jeedom-plugin-connexoon#8]
Depuis une semaine mes volets ne répondent plus et quand j essayé de reconnecter à connexoon j ai une 401 alors que mes info sont ok.

Un changement dans l api côté Somfy?

**Comment by benjaminprevot** [comment]
Pas de changement à ma connaissance.

Mais le problème d'authentification est malheureusement toujours d'actualité : https://community.jeedom.com/t/connexion-impossible-sur-le-plugin-connexoon-api-somfy/38181

Somfy est muet sur le sujet.

A suivre...

**Comment by ahyear** [comment]
Apparement c'est plutôt côté jeedom qu'il semble y avoir un problème...
A partir du moment où on lance le refresh du token, ça invalide la session jeedom. D'où le 401...

J'ai remarque que je suis force de me relogger après chaque tentative.

**Comment by benjaminprevot** [comment]
Y a-t-il des message dans les logs ?

**Comment by benjaminprevot** [comment]
L'API Somfy a complètement changé.

Le plugin est en cours de réécriture et les fonctionnalités de base sont de nouveau disponibles.

Il est possible de le mettre à jour et d’interagir avec les volets.

Je ferme ce ticket.

Si besoin, n'hésitez pas à en ouvrir un nouveau concernant la nouvelle version.
